export const REQUEST_ARTIST_LIST = 'REQUEST_ARTIST_LIST';
export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS';
export const RECEIVE_ARTIST = 'RECEIVE_ARTIST';
export const RECEIVE_ARTIST_TOP_TRACKS = 'RECEIVE_ARTIST_TOP_TRACKS';
export const REQUEST_OWNED_ARTISTS = 'REQUEST_OWNED_ARTISTS';
export const RECEIVE_OWNED_ARTISTS = 'RECEIVE_OWNED_ARTISTS';
