export const REQUEST_USER_PROFILE = 'REQUEST_USER_PROFILE';
export const RECEIVE_USER_PROFILE = 'RECEIVE_USER_PROFILE';
export const RECEIVE_OWNED_ARTISTS = 'RECEIVE_OWNED_ARTISTS';
export const REQUEST_OWNED_ARTISTS = 'REQUEST_OWNED_ARTISTS';
